### ISSUE TITLE
So strange code

### ISSUE THREAD

**Issue by mrfoe7** [AndrusGerman/go-socket.io-issues-229#1]
Hi, Andrus!

Why are you use this code by next [line](https://github.com/AndrusGerman/go-socket.io-issues-229/blob/master/main.go#L14)?

**Comment by AndrusGerman** [comment]
@mrfoe7  The run.sh file does not have the ability to stop the execution of [main](https://github.com/AndrusGerman/go-socket.io-issues-229/blob/master/main.go) for this reason I put something self-destructive
